### ISSUE TITLE
[sqlserver] Soda-sql fails to analyze Sqlserver column with special character

### ISSUE THREAD

**Issue by ashitabh** [sodadata/soda-sql#325]
Sqlserver column name: "Trst/Dept"
Command: soda analyze
```
Error: 
  COUNT(CASE WHEN Trst/Dept LIKE '^((\+\d{1,2}\s)?\(?\d{3}\)?[\s.-])?\d{3}[\s.-]\d{4}$' THEN 1 END),
  COUNT(CASE WHEN Trst/Dept LIKE '^\d{16}|(\d{4}-){3}\d{4}|(\d{4} ){3}\d{4}$' THEN 1 END),
  COUNT(Trst/Dept)
FROM (SELECT TOP 1000 * FROM "Stg"."Tbl_XXX") T
  | Exception: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Trst'. (207) (SQLExecDirectW); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Dept'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Trst'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Dept'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Trst'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Dept'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Trst'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Dept'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Trst'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Dept'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'Trst'. (207); [42S22] [Microsoft][ODBC Driver 17 for SQL Server][S
```

**Comment by ashitabh** [comment]
For a workaround, I added quotename for column names (sqlserver_dialect.py) and added square brackets in yml
  sql = (f"SELECT QUOTENAME(column_name), data_type, is_nullable \n"
               f"FROM information_schema.columns \n"
               f"WHERE lower(table_name) = '{table_name}'")

yml 
columns:
  "[Trst/Dept]":
    valid_max_length: 5
    valid_min_length: 0
    tests:
      - valid_percentage == 100

**Comment by gustavorps** [comment]
+1

```
SELECT 
  COUNT(CASE WHEN  M       LIKE '^\-?\d+$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^\-?\d+\.\d+$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^\-?\d+,\d+$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^\-?\d+([\.,]\d+)? ?%$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^(\$)? ?(\-)?(\d+[,])*(\d+)(\.\d+)? ?(\$|usd|USD)?$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^(€)? ?(\-)?(\d+[ ])*(\d+)(,\d+)? ?(€|eur|EUR)?$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^(£)? ?(\-)?(\d+[,])*(\d+)(\.\d+)? ?(£|gbp|GBP)?$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^(¥)? ?(\-)?(\d+[,])*(\d+)(\.\d+)? ?(¥|rmb|RMB)?$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^(CHf)? ?(\-)?(\d+[''])*(\d+)(\.\d+)? ?(CHf|chf|CHF)?$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^(((\$)? ?(\-)?(\d+[,])*(\d+)(\.\d+)? ?(\$|usd|USD)?)|((€)? ?(\-)?(\d+[ ])*(\d+)(,\d+)? ?(€|eur|EUR)?)|((£)? ?(\-)?(\d+[,])*(\d+)(\.\d+)? ?(£|gbp|GBP)?)|((¥)? ?(\-)?(\d+[,])*(\d+)(\.\d+)? ?(¥|rmb|RMB)?)|((CHf)? ?(\-)?(\d+[''])*(\d+)(\.\d+)? ?(CHf|chf|CHF)?))$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^([1-9]|0[1-9]|[12][0-9]|3[01])[-\./]([1-9]|0[1-9]|1[012])[-\./](19|20)?\d\d' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^([1-9]|0[1-9]|1[012])[-\./]([1-9]|0[1-9]|[12][0-9]|3[01])[-\./](19|20)?\d\d' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^(19|20)\d\d[-\./]?([1-9]|0[1-9]|1[012])[-\./]?([1-9]|0[1-9]|[12][0-9]|3[01])' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '([0-9]|1[0-9]|2[0-4])[:-]([0-9]|[0-5][0-9])([:-]([0-9]|[0-5][0-9])(,\d+)?)?$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^([1-9]\d{3}-((0[1-9]|1[0-2])-(0[1-9]|1\d|2[0-8])|(0[13-9]|1[0-2])-(29|30)|(0[13578]|1[02])-31)|([1-9]\d(0[48]|[2468][048]|[13579][26])|([2468][048]|[13579][26])00)-02-29)T([01]\d|2[0-3]):[0-5]\d:[0-5]\d(\.\d+)?(Z|[+-][01]\d:[0-5]\d)?$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^[0-9a-fA-F]{8}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{4}\-[0-9a-fA-F]{12}$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^[A-Za-z0-9.-_%]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,4}$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^((\+\d{1,2}\s)?\(?\d{3}\)?[\s.-])?\d{3}[\s.-]\d{4}$' THEN 1 END),
  COUNT(CASE WHEN  M       LIKE '^\d{16}|(\d{4}-){3}\d{4}|(\d{4} ){3}\d{4}$' THEN 1 END),
  COUNT( M      ) 
FROM (SELECT TOP 1000 * FROM "dbo"."OMS_Altura_2_5_percentiles") T
  | Exception: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'M'. (207) (SQLExecDirectW)")
Traceback (most recent call last):
  File "/home/gustavorps/.local/miniconda3/lib/python3.9/site-packages/sodasql/cli/cli.py", line 240, in analyze
    dataset_analyze_results = dataset_analyzer.analyze(warehouse, table_name)
  File "/home/gustavorps/.local/miniconda3/lib/python3.9/site-packages/sodasql/dataset_analyzer.py", line 72, in analyze
    row = warehouse.sql_fetchone(
  File "/home/gustavorps/.local/miniconda3/lib/python3.9/site-packages/sodasql/scan/warehouse.py", line 27, in sql_fetchone
    return sql_fetchone(self.connection, sql)
  File "/home/gustavorps/.local/miniconda3/lib/python3.9/site-packages/sodasql/scan/db.py", line 20, in sql_fetchone
    return sql_fetchone_description(connection, sql)[0]
  File "/home/gustavorps/.local/miniconda3/lib/python3.9/site-packages/sodasql/scan/db.py", line 33, in sql_fetchone_description
    cursor.execute(sql)
pyodbc.ProgrammingError: ('42S22', "[42S22] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Invalid column name 'M'. (207) (SQLExecDirectW)")
```

**Comment by vijaykiran** [comment]
Fixed in the latest tag.
