### ISSUE TITLE
[core] valid_min doesn't validate the values passed

### ISSUE THREAD

**Issue by vijaykiran** [sodadata/soda-sql#402]
If someone made mistake in scan YAML by adding `min_length` to `valid_min` like this:

```yaml
columns:
  feepct:
    valid_min:
      - min_length == 7
    tests:
      - invalid_percentage == 0
```

Since Soda SQL doesn't validate the valid_min to be a value it uses whatever yaml parser is giving as value, resulting in sending the list to soda scan start command:

```sh
❯ soda scan warehouse.yml tables/demodata.yml
  | 2.1.0b12
  | Scanning tables/demodata.yml ...
  | Environment variable SODA_POSTGRES_PORT is not set
  | Environment variable SODA_POSTGRES_PASSWORD is not set
  | Soda cloud: dev.sodadata.io
  | Soda Cloud scan start
  | executing {'type': 'sodaSqlScanStart', 'warehouseName': 'test', 'warehouseType': 'postgres', 'tableName': 'demodata', 'scanTime': '2021-07-26T10:05:14+00:00', 'columns': {'feepct': {'validity': {'namedFormat': None, 'regexFormat': None, 'validValues': None, 'minLength': None, 'maxLength': None, 'minValue': ['min_length == 7'], 'maxValue': None}}}, 'origin': 'external'}

```
Notice `minValue` above.

This results in an exception in Soda SQL scan 

```sh
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/vijay/.pyenv/versions/3.9.4/lib/python3.9/logging/__init__.py", line 1083, in emit
    msg = self.format(record)
  File "/Users/vijay/.pyenv/versions/3.9.4/lib/python3.9/logging/__init__.py", line 927, in format
    return fmt.format(record)
  File "/Users/vijay/.pyenv/versions/3.9.4/lib/python3.9/logging/__init__.py", line 663, in format
    record.message = record.getMessage()
  File "/Users/vijay/.pyenv/versions/3.9.4/lib/python3.9/logging/__init__.py", line 367, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Call stack:
  File "/Users/vijay/.pyenv/versions/soda-sql-main/bin/soda", line 33, in <module>
    sys.exit(load_entry_point('soda-sql-core==2.1.0b12', 'console_scripts', 'soda')())
  File "/Users/vijay/.pyenv/versions/3.9.4/envs/soda-sql-main/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/vijay/.pyenv/versions/3.9.4/envs/soda-sql-main/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/vijay/.pyenv/versions/3.9.4/envs/soda-sql-main/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/vijay/.pyenv/versions/3.9.4/envs/soda-sql-main/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/vijay/.pyenv/versions/3.9.4/envs/soda-sql-main/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/vijay/.pyenv/versions/3.9.4/envs/soda-sql-main/lib/python3.9/site-packages/sodasql/cli/cli.py", line 364, in scan
    scan_result: ScanResult = scan.execute()
  File "/Users/vijay/.pyenv/versions/3.9.4/envs/soda-sql-main/lib/python3.9/site-packages/sodasql/scan/scan.py", line 87, in execute
    self._query_aggregations()
  File "/Users/vijay/.pyenv/versions/3.9.4/envs/soda-sql-main/lib/python3.9/site-packages/sodasql/scan/scan.py", line 339, in _query_aggregations
    logging.debug(f'Exception during aggregation query', e)
Message: 'Exception during aggregation query'
Arguments: (SyntaxError('syntax error at or near "["\nLINE 24: ...^-\\d\\.\\,]\', \'\', \'g\'), \'\\,\', \'.\', \'g\') AS REAL) >= [\'min_leng...\n

```

It would be nice if soda-sql can show the error when parsing the YAML instead of making it an error during scan.

**Comment by vijaykiran** [comment]
Fixed via https://github.com/sodadata/soda-sql/commit/78bae4c223b3e04012049d72b14146bd19c71954
