### ISSUE TITLE
JSON column type support

### ISSUE THREAD

**Issue by milanaleksic** [sodadata/soda-sql#87]
For this PostgreSQL table:

```sql
CREATE TABLE test_table (
    varchar_with_nulls_ VARCHAR(255),
    text_custom_missing_ TEXT,
    char_eu_date_ CHAR(10),
    varchar_percent_ VARCHAR(10),
    double_precision_ DOUBLE PRECISION,
    integer_ INTEGER,
    bytea_all_nulls_ BYTEA,
    timestamp_ TIMESTAMP,
    time_ TIME,
    date_ DATE,
    json_ JSON
);
```

profiling fails since data type `JSON` is not supported:

```
14:13:46.322 INFO  PostgresCo | STDERR: STATEMENT:  WITH group_by_value AS ( 
14:13:46.322 INFO  PostgresCo | STDERR: 	  SELECT 
14:13:46.322 INFO  PostgresCo | STDERR: 	    json_ AS value, 
14:13:46.322 INFO  PostgresCo | STDERR: 	    COUNT(*) AS frequency 
14:13:46.322 INFO  PostgresCo | STDERR: 	  FROM "public"."test_table" 
14:13:46.322 INFO  PostgresCo | STDERR: 	  WHERE NOT (json_ IS NULL) 
14:13:46.322 INFO  PostgresCo | STDERR: 	  GROUP BY json_ 
14:13:46.322 INFO  PostgresCo | STDERR: 	) 
14:13:46.322 INFO  PostgresCo | STDERR: 	SELECT COUNT(*), 
14:13:46.322 INFO  PostgresCo | STDERR: 	       COUNT(CASE WHEN frequency = 1 THEN 1 END), 
14:13:46.322 INFO  PostgresCo | STDERR: 	       SUM(frequency) 
14:13:46.322 INFO  PostgresCo | STDERR: 	FROM group_by_value
14:13:46.326 INFO  SodaScanne | STDOUT: Scan failed
14:13:46.326 INFO  SodaScanne | STDOUT: Traceback (most recent call last):
14:13:46.326 INFO  SodaScanne | STDOUT:   File "/usr/local/lib/python3.8/site-packages/sodasql/scan/scan.py", line 77, in execute
14:13:46.326 INFO  SodaScanne | STDOUT:     self._query_group_by_value()
14:13:46.326 INFO  SodaScanne | STDOUT:   File "/usr/local/lib/python3.8/site-packages/sodasql/scan/scan.py", line 275, in _query_group_by_value
14:13:46.327 INFO  SodaScanne | STDOUT:     query_result_tuple = self.warehouse.sql_fetchone(sql)
14:13:46.327 INFO  SodaScanne | STDOUT:   File "/usr/local/lib/python3.8/site-packages/sodasql/scan/warehouse.py", line 27, in sql_fetchone
14:13:46.327 INFO  SodaScanne | STDOUT:     return sql_fetchone(self.connection, sql)
14:13:46.327 INFO  SodaScanne | STDOUT:   File "/usr/local/lib/python3.8/site-packages/sodasql/scan/db.py", line 20, in sql_fetchone
14:13:46.327 INFO  SodaScanne | STDOUT:     return sql_fetchone_description(connection, sql)[0]
14:13:46.327 INFO  SodaScanne | STDOUT:   File "/usr/local/lib/python3.8/site-packages/sodasql/scan/db.py", line 33, in sql_fetchone_description
14:13:46.327 INFO  SodaScanne | STDOUT:     cursor.execute(sql)
14:13:46.327 INFO  SodaScanne | STDOUT: psycopg2.errors.UndefinedFunction: could not identify an equality operator for type json
14:13:46.328 INFO  SodaScanne | STDOUT: LINE 7:   GROUP BY json_ 
```

**Comment by milanaleksic** [comment]
This is tested under https://github.com/sodadata/soda/blob/90bb81c83c03d3197ca1295e8c9d70902e8c6725/soda-integration-tests/src/test/java/io/soda/integration/tests/sql/LongSodaSqlIntegrationTest.java#L441-L440
